resources:
  db:
    type: postgres
    options:
      class: db.t4g.small
      version: 14
      storage: 50
services:
  n8n:
    build: .
    domain: ${HOST}
    environment:
      - DB_TYPE=postgresdb
      - N8N_PORT=5678
      - N8N_USER_MANAGEMENT_DISABLED=true
    port: 5678
    resources:
      - db
    volumes:
      - /home/node/.n8n