resources:
  db:
    type: postgres
    options:
      class: db.t4g.small
      version: 14
      storage: 50
services:
  n8n:
    build: .
    domain: ${HOST}
    environment:
      - DB_TYPE=postgresdb
      - N8N_PORT=5678
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_SSL=true
      - N8N_HOST=
      - N8N_EDITOR_BASE_URL=
      - N8N_SMTP_HOST=
      - N8N_SMTP_PORT=
      - N8N_SMTP_USER=
      - N8N_SMTP_PASS=
      - N8N_SMTP_SENDER=
    port: 5678
    resources:
      - db
    volumes:
      - /home/node/.n8n